version: '2'
services:

  webapp:
    image: gigiosouza/fiap-docker-webapp
    ports:
      - '4200:80'
    links:
      - api
    depends_on:
      - api

  api:
    image: gigiosouza/fiap-docker-api
    environment:
      DB_NAME: 'go'
      DB_USER: 'root'
      DB_PASSWORD: 123456
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: gigiosouza/fiap-docker-mysql
    ports:
      - '3306:3306'
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_DATABASE: 'go'
      MYSQL_ROOT_PASSWORD: 123456